# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/luuk/code/smpc/gui/ui/broadcast.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(459, 115)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 441, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.partyName = QtWidgets.QLabel(self.frame)
        self.partyName.setGeometry(QtCore.QRect(186, 10, 71, 20))
        self.partyName.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.partyName.setText("")
        self.partyName.setObjectName("partyName")
        self.partyName_2 = QtWidgets.QLabel(self.frame)
        self.partyName_2.setGeometry(QtCore.QRect(40, 50, 151, 21))
        self.partyName_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.partyName_2.setText("")
        self.partyName_2.setObjectName("partyName_2")
        self.partyName_3 = QtWidgets.QLabel(self.frame)
        self.partyName_3.setGeometry(QtCore.QRect(250, 50, 141, 20))
        self.partyName_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.partyName_3.setText("")
        self.partyName_3.setObjectName("partyName_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
