# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/luuk/code/smpc/gui/ui/subroutine.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(459, 169)
        Form.setStyleSheet("\"backgroundColor: blue;\"")
        self.subrouteName = QtWidgets.QLabel(Form)
        self.subrouteName.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.subrouteName.setObjectName("subrouteName")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(0, 30, 461, 141))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.subrouteName.setText(_translate("Form", "TextLabel"))
